//
//  Herbs.swift
//  Grow It
//
//  Created by Apprenant 76 on 28/04/2023.
//

import Foundation

struct  Herbs: Identifiable {
    
    var id = UUID()
    var image: String
    var name: String
    var sun: (String, String)
    var water: (String, String)
    var tools: (String, String)
    var description: String
    var benefits: String
    var howTo: String
    var tips: String
    var pair: String
}

let basilicGV = Herbs(image: "basilic1", name: "Basilic Grand Vert", sun: ("sun", "sunLight"), water: ("waterdrop", "waterdropLight"), tools: ("shovel","shovelLight"), description: "Le Basilic Grand Vert est une variété particulièrement parfumée et est également connu sous le nom de basilic à grandes feuilles. De culture facile, le Basilic Grand Vert se plante à la mi-mai et se récolte de mai à octobre et demande peu d’entretien", benefits: "Le Basilic Grand Vert permet de lutter efficacement contre les troubles gastriques et les ballonnements. Il est aussi utilisé pour ses propriétés antalgiques, sédatives et calmantes.", howTo: "Installez 1 à 2 cm de billes d’argile ou de pouzzolane au fond d’un pot percé, et couvrez de terreau universel. Munissez-vous d’un pulvérisateur à eau afin d’arroser le jeune plant de basilic Grand Vert. Lorsque le plant a bien repris, arrosez-le par le haut ou bassinez le pot. Gardez-le dans un endroit lumineux. Concernant son arrosage, le substrat doit rester toujours humide.", tips: "Pour la récolte, munissez vous de ciseaux ! Vous pourrez conserver vos feuilles dans une boite hermétique ou bien les faire sécher.", pair: "Les feuilles fraîches ou séchées pourront être consommées dans la composition de salades, de marinades et de sauce qui accompagnerons parfaitement les plats de pâtes, de viandes ou de poissons.")

let aneth = Herbs(image: "aneth", name: "Aneth", sun: ("sun", "sunLight"), water: ("waterdrop", "waterdropLight"), tools: ("shovel","shovelLight"), description: "Originaire d'Asie mineure, l'aneth est mentionné dans un traité médical égyptien remontant à 5 000 ans. Autrefois, il poussait spontanément sur le pourtour méditerranéen avant d'atteindre la péninsule ibérique et l'Europe de l'est (la Bulgarie et la Roumanie notamment). L'aneth pousse au bord des chemins ou sur les terrains vagues ; il aime les sols secs et pierreux. On le récolte principalement dans les pays scandinaves, la Russie et la Grande-Bretagne,", benefits: "L'aneth est une plante championne des propriétés médicinales. On lui reconnaît des vertus digestives, stimulantes, excellente pour stimuler l'appétit et les fonctions d'élimination et c'est également un formidable calmant naturel.", howTo: "Remplir les potées ou les jardinières si possible de terre de jardin, éventuellement allégée par un peu de terreau.Veillez à arroser régulièrement votre aneth afin que la surface du terreau reste toujousr fraîche.", tips: "L'aneth, se déguste pendant les mois de juin à septembre et est très utile pour lutter contre le hoquet ! Installez l'aneth de préférence à exposition ensoleillée.", pair: "Indissociable du saumon, les recettes à l'aneth fait pourtant des miracles avec d'autres ingrédients. En sushi, salade, galette salée ou cake, cette petite herbe aromatique est très prisée pour des plats de la mer comme de la terre.")

let ciboulette = Herbs(image: "ciboulette", name: "Ciboulette", sun: ("sun", "sunLight"), water: ("waterdrop", "waterdropLight"), tools: ("shovel","shovelLight"), description: "La ciboulette est une plante vivace cousine de l'oignon, au feuillage caduc. Elle forme rapidement des touffes compactes, munies de longues et fines feuilles cylindriques, creuses. A leur base se développent des petits bulbes oblongs.", benefits: "La ciboulette comble les carences d'un régime alimentaire déséquilibré car elle contient des vitamines C, B2 et K, du calcium, du sodium, du phosphore et du fer. Bénéfique pour la circulation du sang, elle favorise l'élasticité des vaisseaux et les préserve d'un vieillissement prématuré.", howTo: "Semer directement dans le pot, idéalement rempli de terreau. Une fois en place, la ciboulette réclame peu d’entretien, elle pousse toute seule et se multiplie facilement. Coupez régulièrement les fleurs afin d’éviter que la plante ne monte en graine. ", tips: "Ne jetez pas vos fleurs de ciboulette car... Elles se mangent ! Vous pouvez croquez dedans ou bien les utiliser pour décorer vos plats.", pair: "La ciboulette est une excellente plante pour accompagner les salades, les sauces, les fromages frais et les omelettes durant tout l’été et jusqu’au début de l’automne.")

let romarin = Herbs(image: "romarin", name: "Romarin", sun: ("sun", "sunLight"), water: ("waterdrop", "waterdropLight"), tools: ("shovel","shovelLight"), description: "Le Romarin Officinal, ou de son nom scientifique “Rosmarinus Officinalis”, se caractérise par son feuillage vert et ses branches ramifiées. Originaire du bassin méditerranéen, cette plante du soleil parfume nos plats de saveurs provençales. C'est une plante robuste et facile à cultiver", benefits: "Le romarin a un riche apport nutritionnel : Vitamine C, thiamine et riboflavine. Il aide à la digestion, à l'élimination et au drainage, à renforcer le système immunitaire, stimule la mémoire et la concentration, a un effet antioxydant et aide à soulager les infections respiratoires et ORL", howTo: "Plantez le romarin au printemps ou en automne (en septembre jusque fin octobre), dans un mélange de terreau, de terre du jardin et d'un peu de sable pour accentuer le pouvoir drainant. Le romarin est une plante aromatique qui n'aime pas l'humidité et qui a besoin de beaucoup de soleil; il est donc nécessaire de bien drainer la terre pour évacuer l'eau.", tips: "Gardez votre romarin dans un pot percé afin d'aider au bon drainage de l'eau !", pair: "Le romarin est très aromatisant et se prête particulièrement aux grillades de viandes et de poissons.")

let origan = Herbs(image: "origan", name: "Origan", sun: ("sun", "sunLight"), water: ("waterdrop", "waterdropLight"), tools: ("shovel","shovelLight"), description: "Aussi connu sous l’appellation « marjolaine vivace » ou encore Origanum vulgare, l’origan est une plante aromatique vivace et rustique, très robuste et globalement simple à cultiver. Ses feuilles, réputées pour leurs arômes fins et subtils, sont très présentes dans les recettes italiennes, mais vous pouvez aussi vous en servir plus généralement pour relever toutes sortes de plats, avec d’autres herbes aromatiques pour jouer sur les contrastes.", benefits: "L'origan est tonique, digestif, stimulant et purgatif. Fortement dosé, il stimule le cœur. L'origan est une plante largement utilisée en phytothérapie sous forme d'infusions ou d'huiles essentielles. On lui reconnaît des vertus antalgiques, anti-infectieuses, antiseptiques et antibactériennes.", howTo: "En pot, vous pouvez laisser sécher la terre en surface (sur 2-3 cm) entre deux arrosages. Attention à ne jamais laisser d’eau stagnante dans les soucoupes pour éviter que les racines ne pourrissent. Lors des grosses chaleurs estivales, un arrosage quotidien est nécessaire. Si l’hiver est sec et que votre origan ne reçoit pas directement l’eau de la pluie, continuez à l’arroser en espaçant les arrosage et en laissant toujours sécher la terre en surface.", tips: "L'origan est une plante peu gourmande,  l’apport d’engrais lui est inutile.", pair: "L'origan s’utilise pour parfumer les sauces, les légumes, les viandes et la charcuterie. Mais surtout, il deviendra un indispensable pour vos pizzas maison !")

let estragon = Herbs(image: "estragon", name: "Estragon", sun: ("sun", "sunLight"), water: ("waterdrop", "waterdropLight"), tools: ("shovel","shovelLight"), description: "L'estragon (Artemisia dracunculus), originaire de la Russie et de Mongolie, est une plante aromatique vivace qui fait partie de la famille des Astéracées. Il se présente en tiges très ramifiées, couvertes de longues feuilles vertes et satinées. Il peut facilement former une touffe de 80 cm de haut", benefits: "L'estragon est excellent pour stimuler votre appétit et dynamiser la digestion, grâce à la vitamine C. Il s'avère tout aussi efficace en cas de ballonnements, d'aérophagie et de douleurs à l'estomac. Il assure un bon transit. On le recommande en cas de légère constipation.", howTo: "La plantation se fait au printemps, d’avril à juin pour des récoltes quasi immédiates et, sur une longue période, jusqu’en octobre. Étalez une couche de gravillons ou billes d’argile au fond d’un pot ou d’une jardinière percée pour assurer le drainage puis recouvrir de terreau. Placez ensuite la mini-motte très délicatement et comblez avec le reste du terreau", tips: "Utilisez un terreau riche pour potager et plantes aromatiques qui retienne bien l’eau et fournira à votre estragon les éléments indispensables à sa bonne croissance.. L’estragon apprécie un substrat riche, bien drainé et restant légèrement humide, mais pas détrempé. Vous pouvez alléger le terreau avec un peu de sable, il apprécie les substrats un peu sablonneux.", pair: "Les  feuilles de l'estragon s’utilisent aussi bien fraîchement ciselées que séchées pour agrémenter les sauces, les poissons ou encore les volailles.")

let ail = Herbs(image: "ail", name: "Ail", sun: ("sun", "sunLight"), water: ("waterdrop", "waterdropLight"), tools: ("shovel","shovelLight"), description: "L'ail est une plante herbacée à bulbe formé de 3 à 15 gousses appelées aussi caïeux, et qui sont en fait des bourgeons tubérisés par lesquels se fait la multiplication de la plante.", benefits: "L'ail est un véritable médicament, grâce à ses propriétés antimicrobiennes, antiseptiques, anti-inflammatoires, anti-bactériennes, antifongiques et même antivirales. Il est donc conseillé d'en consommer pour lutter contre les maux et maladies infectieuses come le rhume, le mal de gorge ou encore l'angine de poitrine.", howTo: "Pour cultiver votre ail, il suffit de choisir un contenant adapté (d'une hauteur d'au moins 20cm de profondeur) et de le remplir d’un substrat de culture sans terre, afin d’y planter vos bulbes. Une fois que les plants ont 5 ou 6 feuilles, et que ces dernières jaunissent, votre ail est prêt à être récolté. Ainsi, au bout d’environ 10 mois, il ne vous restera plus qu’à arracher les bulbes, les faire sécher dans un endroit sec et tempéré pendant une semaine, et vous régaler !", tips: "Choisissez donc un pot percé d’un trou en son fond, permettant ainsi à l’eau excédentaire d’être convenablement évacuée. Cette précaution évite le pourrissement de l’ail.", pair: "La meilleure façon de consommer de l'ail est crue dans une recette de sauce vinaigrette, pesto, persillade ou tartare. Vous pouvez aussi utiliser une gousse d'ail coupée pour frotter des tranches de pain ou un plat à gratin afin de donner du goût")

let menthe = Herbs(image: "menthe", name: "Menthe Verte", sun: ("sun","sunLight"), water: ("waterdrop","waterdropLight"), tools: ("shovel","shovelLight"), description: "La menthe propose une gamme étendue de parfums, d’arômes et de saveurs intenses et rafraîchissantes. Elle est indispensable au jardin car attire les abeilles.", benefits: "La menthe a des qualités antiseptiques qui facilitent la digestion en agissant comme un baume stimulant tout au long du parcours des aliments et régularisent les fonctions de l’estomac, du foie, de la bile, et des intestins. Elle éloigne les insectes et soulage du mal des transports.", howTo: "La menthe se plante en avril une fois les gelées passées. La menthe s'adapte à tous les types de climats français, sur un sol léger et riche en matières organiques(pH : Sol neutre) et bien drainé mais lègerement humide avec une expositon à l'ombre", tips: "La menthe se récolte de Mars à Octobre, on consomme la partie feuillage. Il est possible de la faire sécher ou de la consommer fraiche", pair: "Les feuilles de menthe sont souvent utilisées dans les cuisines méditerranéennes comme par exemple le taboulé et le thé. Dans les pays asiatiques, on l'utilise aussi pour la fabrication des nems et des salades.")

let thym = Herbs(image: "thym", name: "Thym", sun: ("sun","sunLight"), water: ("waterdrop","waterdropLight"), tools: ("shovel","shovelLight"), description: "Le thym est une formidable plante aromatique en cuisine. Il est très résistant, a besoin de soleil et pousse à l'état sauvage sur les collines arides et rocailleuses des régions méditerranéennes. Le thym se sème d'avril à mai et se récolote toute l'année.", benefits: "Le thym a des vertus médicinales, il favorise la digestion et calme l’organisme. De plus, son huile essentielle est réputée antibactérienne et anti-mauvaises odeurs. Elle peut donc être utilisée pour laver le sol ou pour lustrer des surfaces telles qu'un plan de travail.", howTo: "Le thym a besoin de soleil pour se développer, il tolère tous types de sol, même pauvre et caillouteux, un arrosage régulier est recommandé la 1ère année suivant la mise en place mais sans excès et si il ne pleut pas. Semer le thym avec du terreau spécial semis, recouvrir légèrement les graines, arroser en pluie fine. On peut aussi bien semer du thym que planter de jeunes plants achetés en godet.", tips: "Le thym est une plante facile de culture et d’entretien, vous pourrez couper les branches dont vous avez besoin tout au long de l’année. On évitera de couper le thym en période de gel, au risque de le perdre.",pair: "Le thym est très aromatisant et se prête particulièrement aux grillades de viandes et de poissons. On l’utilise également pour parfumer les sauces et les soupes. Le thym est également l'ami des pommes de terre, du pain ou des pâtes brisées : quelques feuilles de thym incorporées à vos pâtes leur confèrent un goût inimitable.")

let persil = Herbs(image: "persil", name: "Persil", sun: ("sun","sunLight"), water: ("waterdrop","waterdropLight"), tools: ("shovel","shovelLight"), description: "Le persil est la plante condimentaire la plus employée dans la cuisine française. Le persil adore les emplacements pas trop chauds et les terres riches, restant frais. Le persil est une plante aromatique facile d’entretien.", benefits: "Les feuilles fraîches du persil sont riches en vitamines et en minéraux. Leur pouvoir antioxydant aide à lutter contre l’apparition des maladies cardiovasculaires et d’autres maladies liées au vieillissement des cellules. Le persil offre une action bénéfique sur le foie, la rate, les intestins et l’ensemble du système digestif, il a des effets antianémiques et anticoagulants.", howTo: "Le persil peut être semé dès la fin de l’hiver, tout au long du printemps et de l’été. Former des sillons tous les 10-15 cm environ, enfouir les graines dans 1 à 2 cm et couvrir de terreau, arroser régulièrement en pluie fine. Arroser en cas de fortes chaleurs ou de sécheresse prolongée, protéger le persil avec une cloche ou une petite serre en hiver.", tips: "Les feuilles peuvent être coupées au fur et à mesure des besoins et cela tout au long de l’année, il est préférable de cueillir les feuilles une par une.", pair: "Le persil s’utilise principalement pour aromatiser salades, omelettes et plats en sauce. Notons d’ailleurs qu’en cuisson il ne faut pas hésiter à utiliser les queue qui renferment bien plus d’arôme que les feuilles.")

let sauge = Herbs(image: "sauge", name: "Sauge", sun: ("sun","sunLight"), water: ("waterdrop","waterdropLight"), tools: ("shovel","shovelLight"), description: "La sauge est une plante utilisée en cuisine pour son arôme et en médecine pour ses vertus. Elle se plante de octobre à mai-juin et se récolte toute l'année. La sauge est une plante facile de culture et d’entretien et convient parfaitement à tous les jardiniers.", benefits: "La sauge offre de puissantes propriétés antiseptiques et bactéricides. Elle est notamment excellente pour traiter les inflammations et troubles de la bouche et de la gorge", howTo: "Vous pouvez planter la sauge à partir d’octobre jusqu’au mois de mai-juin en respectant une distance de 25 à 30 cm entre chaque plante. Évitez de planter la sauge durant les fortes chaleurs. La sauge aime le plein soleil mais tolère la mi-ombre. Elle aime les sols bien drainés, même pauvre. La sauge réclame peu de soin et d’entretien lorsqu’elle est bien installée.", tips: "Pour la culture en pot, n’attendez pas que le sol soit totalement sec pour arroser mais sans excès. La sauge se cueille de préférence le matin, du printemps à la fin de l’été mais elle peut aussi se cueillir le reste de la journée. Attendez que la plante ait une bonne touffe avant de cueillir les premières feuilles. Séchées elle se conserve très bien durant de longs mois", pair: "Elle se marie à merveille avec le gibier, la viande de porc et d’agneau rôtie, le veau, le poulet, la dinde ou encore le canard. Elle accompagne bien les poissons en terrine ou en papillote et permet d'assaisonner les pommes de terre et les féculents en général.")

let laurier = Herbs(image: "laurier", name: "Laurier", sun: ("sun","sunLight"), water: ("waterdrop","waterdropLight"), tools: ("shovel","shovelLight"), description: "Originaire d'Asie mineure et du bassin méditerranéen, on en retrouve déjà les traces dans l'Antiquité grecque, où les héros étaient couronnés avec du laurier. Le laurier est souvent utilisé dans la cuisine méditerranéenne. Sa culture est relativement facile.", benefits: "Stimulant du système immunitaire, antiviral, antibactérien, antifongique très puissant, le laurier est indiqué en cas de troubles digestifs (ballonnements, flatulences), dérèglement de la flore intestinale (candidose), gênes buccales (gingivite, aphtes) et douleurs articulaires.", howTo: "Le laurier requiert une préparation au préalable avant d'être cultivé. Il convient de sélectionner de jeunes pousses et de les placer dans un récipient rempli d'eau pour leur faire prendre racine. Les semis ainsi obtenus peuvent être plantés en terre ou en pot. Avant toute chose, pensez à installer une couche de billes d'argile ou de gravier au fond du pot afin que la plante bénéficie d'un bon drainage. Utilisez dans ce cas un mélange composé de terreau de plantation et de terre de jardin. La plantation du laurier se fait de préférence au printemps ou en automne, sous abri et à une température moyenne de 18°C. Il se plait dans un sol humifère, bien drainé, profond et sec.", tips: "Les arbustes doivent être placés dans un emplacement ensoleillé ou semi-ombragé, à l'abri du vent et du froid. Toutefois, il supporte bien les embruns et la sécheresse. ", pair: "Le laurier est excellent dans les ragoûts, les soupes, les sauces, les marinades, les ratatouilles, les pot-au-feu, les daubes, les bouillons, les farces, les pâtés, les terrines, les viandes, le poisson, les boissons ou encore le vin !")

let gingembre = Herbs(image: "gingembre", name: "Gingembre", sun: ("sun","sunLight"), water: ("waterdrop","waterdropLight"), tools: ("shovel","shovelLight"), description: "D’origine asiatique, le gingembre est connu depuis l’antiquité pour son rhizome aromatique aux mille vertus, aussi bien condimentaires que thérapeutiques.", benefits: "Les bienfaits du gingembre sur l'ensemble de l'organisme sont nombreux et variés : il est actif sur la libido, favorise la digestion, atténue les nausées, c'est un excellent antioxydant, anti-inflammatoire et on lui reconnaît aussi des vertus anti-diabétiques et antidouleur.", howTo: "Dans le pot drainé avec des graviers ou des billes d'argile, mettez un substrat composé à parts égales de sable et de terreau de feuilles enrichi de deux poignées de compost.Enfoncez le rhizome – sain, ferme, dodu, choisi en magasin bio – superficiellement, à 2 ou 3 cm sous terre. Tassez bien.", tips: "Une autre technique consiste à placer le rhizome trempant dans l'eau de moitié, afin qu'il fasse ses racines dans le liquide. Il est bon à mettre en terre quand les racines sont bien formées et les pousses sorties. \rDe plus, le gingembre aime être à l'intérieur. Gardez-le au chaud!", pair: "Le gingembre se marie particulièrement bien avec les pommes, fraises, bananes, rhubarbe, kiwis, poire, etc. L'association du gingembre avec le chocolat est toujours une réussite.")

let hysope = Herbs(image: "hysope", name: "Hysope", sun: ("sun","sunLight"), water: ("waterdrop","waterdropLight"), tools: ("shovel","shovelLight"), description: "L'hysope est une plante vivace aux multiples vertus : médicinales, aromatiques (ses feuilles et ses fleurs émettent un parfum chaud, à la fois camphré, mentholé et épicé), condimentaires (ses feuilles fraîches, hachées finement, relèvent de nombreux plats) et ornementales.", benefits: "L'hysope a des propriétés toniques, antiseptiques, expectorantes, digestives, antifongiques et anti-asthmatiques. On l'emploie pour traiter des rhinites, bronchites, otites ou sinusites, fluidifier la digestion et même faire baisser la fièvre.", howTo: "L'hysope doit être plantée ou rempotée au printemps ou à l'automne. Prévoyez un contenant assez grand, et haut (le système racinaire de la plante est développé et a besoin d'espace). Il est nécessaire de garder le sol bien drainé, léger, sec en été. Quant à  l'exposition, l'hysope se plait au soleil ou bien dans un espace mi-ombre", tips: "On peut la multiplier par semis, en février-mars, en terrine, puis une transplantation est effectuée en mai. Les jeunes plants sont mis en place en pleine terre lorsqu'ils mesurent 20cm. On peut aussi diviser la touffe, au printemps, ou procéder par bouturage de tiges, en août, ou encore par marcottage.", pair: "L'hysope s'utilise un peu comme une herbe de Provence pour parfumer les plats mijotés, les tartes salées, quelques légumes sautés au wok …. Pour les fleurs, vous pouvez les utiliser fraîches pour égayer une salade estivale.")

let verveine = Herbs(image: "verveine", name: "Verveine", sun: ("sun","sunLight"), water: ("waterdrop","waterdropLight"), tools: ("shovel","shovelLight"), description: "", benefits: "La verveine possède notamment des propriétés relaxantes, apaisantes et est utilisée en médecine populaire pour le traitement des rhumatismes et des blessures. La verveine aide à réduire les douleurs intestinales et les spasmes et possède des vertus anti-inflammatoires.", howTo: "Choisir un contenant percé en son fond, étaler un lit de billes d'argile au fond du pot, remplir de terreau contenant un engrais à libération lente puis installer la plante. Garder ensuite la verveine dans un endroit chaud et ensoleillé. Arroser immédiatement après la plantation. Arroser régulièrement pendant toute la période de culture. Ne jamais laisser le mélange sécher entre deux arrosages.", tips: "Plante d’amour, de prospérité, de courage et porte bonheur, la verveine entre dans la préparation des plus puissants philtres d’amour. Se frotter la gorge avec ses feuilles vous rend irrésistible et orner son cou de 3 graines en collier permet d’être un(e) excellent(e) amant(e).", pair: "Elle se marie bien avec la rhubarbe, les pêches et les poires côté sucré. Elle parfume à merveille le riz au lait ou la panna cotta. On peut aussi en parfumer un simple gâteau au yaourt. Et côté salé, c'est avec les poissons blancs et le poulet qu'elle s'entend le mieux : son parfum subtil pourra alors ressortir.")

let fenugrec = Herbs(image: "fenugrec", name: "Fenugrec", sun: ("sun","sunLight"), water: ("waterdrop","waterdropLight"), tools: ("shovel","shovelLight"), description: "Le fenugrec est une plante méditerranéenne, une très ancienne plante médicinale que toutes les civilisations de l'Orient à l'Occident ont mise à contribution, y compris comme condiment en usage culinaire.", benefits: "Les graines nutritives de fenugrec sont fréquemment prescrites pour fortifier les personnes affaiblies, en convalescence après une longue maladie infectieuse par exemple. Elles sont également fébrifuges et leurs vertus analgésiques sont mises à profit en cas de gastrite et d'ulcère d'estomac. Le fenugrec est censé augmenter la production de lait chez les femmes allaitant leur bébé. Une infusion à base de graines de fenugrec est aussi préconisée en cas d'angine et de bronchite. En cataplasme, une pâte de graines de fenugrec permet de soigner les brûlures, les abcès, les furoncles et les ulcères, qui mûrissent, crèvent et guérissent ainsi plus rapidement. Les graines de fenugrec rendent aussi l'haleine fraîche.", howTo: "Avant le semis, trempez les graines de Fenugrec dans de l'eau pendant 12h. Le semis s'effectue directement en pleine terre après les derniers risques de gelées, du milieu à la fin printemps. Votre terre doit être légère et l'exposition doit être ensoleillée.", tips: "", pair: "Les graines moulues servent à épicer les currys, mais donnent aussi une « note orientale » aux sauces classiques, aux ragoûts et aux légumes.")
